version: '2'
services:
  gestionstockjhipster-app:
    image: gestionstockjhipster
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gestionstockjhipster-postgresql:5432/GestionStockJhipster
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 9999:9999
  gestionstockjhipster-postgresql:
    extends:
      file: postgresql.yml
      service: gestionstockjhipster-postgresql
